default:
  run_parallel: TRUE
  n_iter: 50000
  init_dir: NULL
  params_check : !expr c("beta_p", "log_rho", "log_gamma", "p_unique", "log_r_mu", "tau_proc")
  spatial: FALSE
  property_obs_effect: FALSE
  out_dir: "out/test"
  model_file: "R/nimble_dynamic.R"

exponential:
  model_dir: "exponential"
  process_type: "exponential"

ricker:
  model_dir: "ricker"
  process_type: "ricker"
  inits_dir: "exponential"

gompertz:
  model_dir: "gompertz"
  process_type: "gompertz"
  inits_dir: "ricker"

jamiesonBrooks:
  model_dir: "jamiesonBrooks"
  process_type: "jamiesonBrooks"
  inits_dir: "ricker"
  params_check : !expr c("beta_p", "log_rho", "log_gamma", "p_unique", "log_r_mu", "tau_proc", "beta_r")

dennisTaper:
  inherits: "jamiesonBrooks"
  model_dir: "dennisTaper"
  process_type: "dennisTaper"


